spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/coursly
    username: pguser
    password: pgpassword
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "3WQJcHo6Dz0Zx5XRK4pA09pUPN2oWWK1FC3O8p7DbWw1fE8PoD"
  accessTokenExpirationMs: 900000 #15 minutes
  refreshTokenExpirationMs: 604800000 # 7 days

cors:
  allowed:
    origins: "http://localhost:5173"
    methods: "*"
    headers: "*"
